/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import com.toedter.calendar.JDateChooser;
import controller.AddCrop_Controller;
import exceptions.MyException;
import java.sql.Date;
import javax.persistence.NoResultException;
import javax.persistence.PersistenceException;
import javax.swing.JOptionPane;
import org.hibernate.HibernateException;
import org.hibernate.JDBCException;
import org.hibernate.exception.JDBCConnectionException;
import static view.MainHome.agregar;
import static view.starter.entrar;
import static view.starter.window;

/**
 *
 * @author black
 */
public class AddCrop_UI extends javax.swing.JPanel {

    AddCrop_Controller controller = new AddCrop_Controller();
    /**
     * Creates new form agregar_cultivo
     */
    public AddCrop_UI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label_tipo_cosecha = new javax.swing.JLabel();
        label_ini_cosecha = new javax.swing.JLabel();
        label_periodo_cosecha = new javax.swing.JLabel();
        cosecha = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        b_registrar_cultivo = new javax.swing.JButton();
        sembrado = new com.toedter.calendar.JDateChooser();
        recosecha = new com.toedter.calendar.JDateChooser();
        ubicacion = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        titulo = new javax.swing.JTextField();
        b_regresar = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 255, 204));
        setMinimumSize(new java.awt.Dimension(1000, 626));
        setPreferredSize(new java.awt.Dimension(1000, 626));

        label_tipo_cosecha.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        label_tipo_cosecha.setText("Tipo de cosecha:");

        label_ini_cosecha.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        label_ini_cosecha.setText("Sembrado:");

        label_periodo_cosecha.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        label_periodo_cosecha.setText("Inicio de cosecha:");

        cosecha.setMaximumRowCount(4);
        cosecha.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Chile Habanero", "Calabaza", "Pepino", "Chile Serrano" }));
        cosecha.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel1.setFont(new java.awt.Font("Dialog", 3, 24)); // NOI18N
        jLabel1.setText("Agregar cosecha");

        b_registrar_cultivo.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        b_registrar_cultivo.setText("Registrar cultivo");
        b_registrar_cultivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_registrar_cultivoActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setText("Ubicacion:");

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setText("Nombre:");

        b_regresar.setText("Regresar");
        b_regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_regresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(327, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_ini_cosecha, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(label_periodo_cosecha, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(label_tipo_cosecha, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(recosecha, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ubicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(2, 2, 2))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sembrado, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cosecha, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(363, 363, 363))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(b_registrar_cultivo, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)))
                .addGap(402, 402, 402))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(b_regresar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(b_regresar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_tipo_cosecha)
                    .addComponent(cosecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_ini_cosecha)
                    .addComponent(sembrado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(label_periodo_cosecha)
                    .addComponent(recosecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(ubicacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(b_registrar_cultivo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74))
        );
    }// </editor-fold>//GEN-END:initComponents
    /**
     * Send the view reference to the controller to add a Crop
     * @param evt 
     */
    private void b_registrar_cultivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_registrar_cultivoActionPerformed
        try{
            controller.add_crop(this);
            returnToHome();
        }
        catch(MyException ex){
            ex.showException(this);
        }
    }//GEN-LAST:event_b_registrar_cultivoActionPerformed
    /**
     * Return to the main menu
     * @param evt 
     */
    private void b_regresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_regresarActionPerformed
        returnToHome();
    }//GEN-LAST:event_b_regresarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_registrar_cultivo;
    private javax.swing.JButton b_regresar;
    public javax.swing.JComboBox cosecha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel label_ini_cosecha;
    private javax.swing.JLabel label_periodo_cosecha;
    private javax.swing.JLabel label_tipo_cosecha;
    public com.toedter.calendar.JDateChooser recosecha;
    public com.toedter.calendar.JDateChooser sembrado;
    public javax.swing.JTextField titulo;
    public javax.swing.JTextField ubicacion;
    // End of variables declaration//GEN-END:variables


    /**
     * Method to change this window with the Home window
     */
    public void returnToHome(){
        window.remove(agregar); 
        entrar.setCropsNamesInList();
        window.add(entrar);
        window.revalidate();
        window.repaint();
        
        window.setVisible(true);
    }
    
    /**
     * 
     * @return seed date as String
     */
    public String getSeedDate(){
        return sembrado.getDateFormatString();
    }
    /**
     *  
     * @return harvest date as String
     */
    public String getHarvestDate(){       
        return recosecha.getDateFormatString();
    }
    /**
     * 
     * @return Title textField text
     */
    public String getTitle(){
        return titulo.getText();
    }
    /**
     * 
     * @return Location textfield text
     */
    public String getUbicacion(){
        return ubicacion.getText();
    }
    /**
     * 
     * @return Selected item on a list as String
     */
    public String getTipo(){
        return cosecha.getSelectedItem().toString();
    }
    /**
     * 
     * @return harvest date as Sql Date
     */
    public Date getRecosecha() {
        Date harvest = new Date(recosecha.getDate().getTime());
        return harvest;
    }
    /**
     * 
     * @return seed date as Sql Date
     */
    public Date getSembrado() {
        Date seed = new Date(sembrado.getDate().getTime());
        return seed;
    }
    
    /**
     * Show in a JOptionPane the persistence exceptions (incomplete)
     * @param ex
     */
    public void showPersistenceExceptions(PersistenceException ex){
        if(ex instanceof NoResultException){
            JOptionPane.showMessageDialog(this, "Información no encontrada" , "ERROR", JOptionPane.ERROR_MESSAGE);
        }else if (ex instanceof JDBCConnectionException){
            JOptionPane.showMessageDialog(this, "Error de conexión" , "ERROR", JOptionPane.ERROR_MESSAGE);
        }else{
            JOptionPane.showMessageDialog(this, "Error" , "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }
}