/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Color;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import static view.Sign_in.mprincipal;
import static view.starter.entrar;
import static view.starter.window;

/**
 *
 * @author black
 */
public class MainHome extends javax.swing.JPanel {

    /**
     * Creates new form registro_cultivo
     */
    
    public static Sign_in presentacion;        
    public static AddCrop_UI agregar; 
    public static ReportPlague_UI reporte;
    public int count;
    
    public MainHome() {
        initComponents();       
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Main_tabbed_panel = new javax.swing.JTabbedPane();
        panel_mapa = new javax.swing.JPanel();
        table_news_scroll = new javax.swing.JScrollPane();
        table_news = new javax.swing.JTable();
        table_cultivo_scroll = new javax.swing.JScrollPane();
        table_cultivo = new javax.swing.JTable();
        button_clo_ses = new javax.swing.JButton();
        add_cultivo = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 204, 204));
        setMaximumSize(new java.awt.Dimension(1000, 626));
        setMinimumSize(new java.awt.Dimension(1000, 626));
        setPreferredSize(new java.awt.Dimension(1000, 626));

        Main_tabbed_panel.setMaximumSize(new java.awt.Dimension(1000, 626));
        Main_tabbed_panel.setMinimumSize(new java.awt.Dimension(1000, 626));
        Main_tabbed_panel.setPreferredSize(new java.awt.Dimension(1000, 626));

        panel_mapa.setBackground(new java.awt.Color(204, 255, 204));
        panel_mapa.setMaximumSize(new java.awt.Dimension(1000, 626));
        panel_mapa.setMinimumSize(new java.awt.Dimension(1000, 626));
        panel_mapa.setPreferredSize(new java.awt.Dimension(1000, 626));

        javax.swing.GroupLayout panel_mapaLayout = new javax.swing.GroupLayout(panel_mapa);
        panel_mapa.setLayout(panel_mapaLayout);
        panel_mapaLayout.setHorizontalGroup(
            panel_mapaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panel_mapaLayout.setVerticalGroup(
            panel_mapaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        Main_tabbed_panel.addTab("Mapa", panel_mapa);

        table_news.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "noticias"
            }
        ));
        table_news_scroll.setViewportView(table_news);

        Main_tabbed_panel.addTab("noticias", table_news_scroll);

        table_cultivo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "cultivos", "mas informacion"
            }
        ));
        table_cultivo_scroll.setViewportView(table_cultivo);

        Main_tabbed_panel.addTab("mis cultivos", table_cultivo_scroll);

        button_clo_ses.setText("cerrar sesion");
        button_clo_ses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_clo_sesActionPerformed(evt);
            }
        });

        add_cultivo.setText("Agregar cultivo");
        add_cultivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_cultivoActionPerformed(evt);
            }
        });

        jButton1.setText("Reportar plaga");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(582, 582, 582)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(add_cultivo)
                        .addGap(47, 47, 47)
                        .addComponent(button_clo_ses))
                    .addComponent(Main_tabbed_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button_clo_ses)
                    .addComponent(add_cultivo)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Main_tabbed_panel, javax.swing.GroupLayout.PREFERRED_SIZE, 602, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );
    }// </editor-fold>//GEN-END:initComponents

    
    private void button_clo_sesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_clo_sesActionPerformed
        // TODO add your handling code here:    
        presentacion = new Sign_in();
        presentacion.setSize(1000, 626);
        
        window.remove(entrar);
        

        window.add(presentacion);
        
        window.repaint();
        window.revalidate();
        
        window.setVisible(true); 
    }//GEN-LAST:event_button_clo_sesActionPerformed

    private void add_cultivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_cultivoActionPerformed

        agregar = new AddCrop_UI();

        agregar.setSize(1000,626);

        window.remove(entrar);

        window.add(agregar);
        window.repaint();
        window.revalidate();
        window.setVisible(true);
    }//GEN-LAST:event_add_cultivoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        reporte = new ReportPlague_UI();
        
        reporte.setSize(1000, 626);
        window.remove(entrar);
        window.add(reporte);
        window.repaint();
        window.revalidate();
        window.setVisible(true); 
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane Main_tabbed_panel;
    private javax.swing.JButton add_cultivo;
    private javax.swing.JButton button_clo_ses;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel panel_mapa;
    private javax.swing.JTable table_cultivo;
    private javax.swing.JScrollPane table_cultivo_scroll;
    private javax.swing.JTable table_news;
    private javax.swing.JScrollPane table_news_scroll;
    // End of variables declaration//GEN-END:variables
}
