/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import static view.Sign_in.mprincipal;
import static view.starter.window;

/**
 *
 * @author black
 */
public class Main_menu extends javax.swing.JPanel {

    /**
     * Creates new form registro_cultivo
     */
    public Main_menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Main_tabbed_panel = new javax.swing.JTabbedPane();
        panel_noticias = new javax.swing.JPanel();
        panel_mapa = new javax.swing.JPanel();
        panel_reg_cult = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 204, 204));
        setMinimumSize(new java.awt.Dimension(1000, 626));
        setPreferredSize(new java.awt.Dimension(1000, 626));

        panel_noticias.setBackground(new java.awt.Color(204, 255, 204));

        javax.swing.GroupLayout panel_noticiasLayout = new javax.swing.GroupLayout(panel_noticias);
        panel_noticias.setLayout(panel_noticiasLayout);
        panel_noticiasLayout.setHorizontalGroup(
            panel_noticiasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 998, Short.MAX_VALUE)
        );
        panel_noticiasLayout.setVerticalGroup(
            panel_noticiasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );

        Main_tabbed_panel.addTab("Noticias", panel_noticias);

        panel_mapa.setBackground(new java.awt.Color(204, 255, 204));

        javax.swing.GroupLayout panel_mapaLayout = new javax.swing.GroupLayout(panel_mapa);
        panel_mapa.setLayout(panel_mapaLayout);
        panel_mapaLayout.setHorizontalGroup(
            panel_mapaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 998, Short.MAX_VALUE)
        );
        panel_mapaLayout.setVerticalGroup(
            panel_mapaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );

        Main_tabbed_panel.addTab("Mapa", panel_mapa);

        panel_reg_cult.setBackground(new java.awt.Color(204, 255, 204));

        jButton1.setText("Agregar cultivo");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_reg_cultLayout = new javax.swing.GroupLayout(panel_reg_cult);
        panel_reg_cult.setLayout(panel_reg_cultLayout);
        panel_reg_cultLayout.setHorizontalGroup(
            panel_reg_cultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_reg_cultLayout.createSequentialGroup()
                .addContainerGap(823, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(67, 67, 67))
        );
        panel_reg_cultLayout.setVerticalGroup(
            panel_reg_cultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_reg_cultLayout.createSequentialGroup()
                .addContainerGap(515, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(60, 60, 60))
        );

        Main_tabbed_panel.addTab("Mis cultivos", panel_reg_cult);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Main_tabbed_panel, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Main_tabbed_panel)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        agregar_cultivo agregar = new agregar_cultivo();
        agregar.setSize(1000,626);
               
        window.remove(mprincipal);
        window.add(agregar);
        window.repaint();
        window.revalidate();
        window.setVisible(true);
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane Main_tabbed_panel;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel panel_mapa;
    private javax.swing.JPanel panel_noticias;
    private javax.swing.JPanel panel_reg_cult;
    // End of variables declaration//GEN-END:variables
}
