/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author black
 */
public class Sign_up extends javax.swing.JPanel {

    /**
     * Creates new form Sign_up
     */
    public Sign_up() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Sign_in_img = new javax.swing.JLabel();
        Name_reg = new javax.swing.JTextField();
        mail_reg = new javax.swing.JTextField();
        Pass_reg = new javax.swing.JPasswordField();
        Pass_reg_conf = new javax.swing.JPasswordField();
        etiqueta_nombre = new javax.swing.JLabel();
        etiqueta_correo = new javax.swing.JLabel();
        etiqueta_contraseña = new javax.swing.JLabel();
        etiqueta_conf_contraseña = new javax.swing.JLabel();
        titulo_registrarse = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 255, 204));
        setPreferredSize(new java.awt.Dimension(1000, 626));

        Sign_in_img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/Tipos-de-chile-en-Mexico-.jpg"))); // NOI18N

        Name_reg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Name_regActionPerformed(evt);
            }
        });

        etiqueta_nombre.setText("Nombre:");

        etiqueta_correo.setText("Correo electronico:");

        etiqueta_contraseña.setText("Contraseña:");

        etiqueta_conf_contraseña.setText("Confirmar contraseña:");

        titulo_registrarse.setFont(new java.awt.Font("Dialog", 3, 24)); // NOI18N
        titulo_registrarse.setForeground(new java.awt.Color(0, 0, 0));
        titulo_registrarse.setText("Registrarse");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Sign_in_img, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(titulo_registrarse, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(402, 402, 402))
            .addGroup(layout.createSequentialGroup()
                .addGap(285, 285, 285)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(etiqueta_nombre, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(etiqueta_correo, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(etiqueta_contraseña, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(etiqueta_conf_contraseña, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Name_reg)
                    .addComponent(mail_reg)
                    .addComponent(Pass_reg)
                    .addComponent(Pass_reg_conf, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(Sign_in_img, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(titulo_registrarse, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Name_reg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etiqueta_nombre))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mail_reg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etiqueta_correo))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Pass_reg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etiqueta_contraseña))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Pass_reg_conf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etiqueta_conf_contraseña))
                .addContainerGap(118, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void Name_regActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Name_regActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Name_regActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Name_reg;
    private javax.swing.JPasswordField Pass_reg;
    private javax.swing.JPasswordField Pass_reg_conf;
    private javax.swing.JLabel Sign_in_img;
    private javax.swing.JLabel etiqueta_conf_contraseña;
    private javax.swing.JLabel etiqueta_contraseña;
    private javax.swing.JLabel etiqueta_correo;
    private javax.swing.JLabel etiqueta_nombre;
    private javax.swing.JTextField mail_reg;
    private javax.swing.JLabel titulo_registrarse;
    // End of variables declaration//GEN-END:variables
}
