/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import static view.Main_menu.presentacion;
import static view.starter.entrar;
import static view.starter.window;

/**
 *
 * @author black
 */
public class Sign_in extends javax.swing.JPanel {

    public static Main_menu mprincipal;
    public static Sign_up registro;
    /**
     * Creates new form Sign_in
     */
    public Sign_in() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Titulo_etiqueta = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Correo_ingreso = new javax.swing.JTextField();
        Contrasena = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        Iniciar_sesion = new javax.swing.JButton();
        No_tienes_cuenta_etiqueta = new javax.swing.JLabel();
        Registrarse = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 255, 204));
        setMaximumSize(new java.awt.Dimension(1000, 626));
        setMinimumSize(new java.awt.Dimension(1000, 626));
        setPreferredSize(new java.awt.Dimension(1000, 626));

        Titulo_etiqueta.setFont(new java.awt.Font("BIZ UDPGothic", 3, 36)); // NOI18N
        Titulo_etiqueta.setForeground(new java.awt.Color(0, 153, 204));
        Titulo_etiqueta.setText("Toj-tu-yéetel");

        jLabel1.setText("Correo:");

        Contrasena.setToolTipText("");
        Contrasena.setName("contraseña"); // NOI18N
        Contrasena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContrasenaActionPerformed(evt);
            }
        });

        jLabel2.setText("Contraseña:");

        Iniciar_sesion.setText("Iniciar Sesión");
        Iniciar_sesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Iniciar_sesionMouseClicked(evt);
            }
        });
        Iniciar_sesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Iniciar_sesionActionPerformed(evt);
            }
        });

        No_tienes_cuenta_etiqueta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        No_tienes_cuenta_etiqueta.setText("¿No tienes una cuenta?");

        Registrarse.setText("Registrate");
        Registrarse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RegistrarseMouseClicked(evt);
            }
        });
        Registrarse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrarseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 316, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(No_tienes_cuenta_etiqueta, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(356, 356, 356))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Titulo_etiqueta, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(Contrasena, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(Correo_ingreso, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 271, Short.MAX_VALUE)))
                        .addGap(319, 319, 319))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(Iniciar_sesion, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(431, 431, 431))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(Registrarse)
                        .addGap(443, 443, 443))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(211, 211, 211)
                .addComponent(Titulo_etiqueta)
                .addGap(71, 71, 71)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Correo_ingreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Contrasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(31, 31, 31)
                .addComponent(Iniciar_sesion)
                .addGap(29, 29, 29)
                .addComponent(No_tienes_cuenta_etiqueta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Registrarse)
                .addGap(0, 118, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ContrasenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContrasenaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ContrasenaActionPerformed

    private void Iniciar_sesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Iniciar_sesionActionPerformed

    }//GEN-LAST:event_Iniciar_sesionActionPerformed

    private void RegistrarseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegistrarseMouseClicked
        // TODO add your handling code here:
        
        //entra al panel de registro de usuario
        registro = new Sign_up();
        registro.setSize(1000,626);
        
        window.remove(presentacion);
        
        window.add(registro);
        
        window.repaint();
        window.revalidate();
        window.setVisible(true);
        

    }//GEN-LAST:event_RegistrarseMouseClicked

    private void RegistrarseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrarseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RegistrarseActionPerformed

    private void Iniciar_sesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Iniciar_sesionMouseClicked
        // TODO add your handling code here:
        
        //entrada al menu principal del usuario
        mprincipal = new Main_menu();
        
        mprincipal.setSize(1000,626);
        window.remove(presentacion);        
        window.add(entrar);
        
        window.repaint();
        window.revalidate();
        window.setVisible(true);
    }//GEN-LAST:event_Iniciar_sesionMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField Contrasena;
    private javax.swing.JTextField Correo_ingreso;
    private javax.swing.JButton Iniciar_sesion;
    private javax.swing.JLabel No_tienes_cuenta_etiqueta;
    private javax.swing.JButton Registrarse;
    private javax.swing.JLabel Titulo_etiqueta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
