/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.HashMap;
import javax.persistence.NoResultException;
import javax.persistence.PersistenceException;
import javax.swing.JOptionPane;
import org.hibernate.HibernateException;
import org.hibernate.JDBCException;
import org.hibernate.exception.JDBCConnectionException;
import static view.MainHome.reporte;
import static view.Sign_in.mprincipal;
import static view.starter.entrar;
import static view.starter.window;

/**
 *
 * @author black
 */
public class TrackCrops_UI extends javax.swing.JPanel {

    /**
     * Creates new form seguimiento_cosechas
     */
    public TrackCrops_UI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fecha_siembra = new javax.swing.JLabel();
        fecha_cosecha = new javax.swing.JLabel();
        Bcosechar = new javax.swing.JButton();
        barra_progreso = new javax.swing.JProgressBar();
        nombre_cosecha = new javax.swing.JLabel();
        B_regresar_mmenu = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        ubicacion = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 255, 204));
        setMaximumSize(new java.awt.Dimension(1000, 626));
        setMinimumSize(new java.awt.Dimension(1000, 626));
        setPreferredSize(new java.awt.Dimension(1000, 626));

        fecha_siembra.setBackground(new java.awt.Color(255, 255, 255));
        fecha_siembra.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        fecha_siembra.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fecha_siembra.setMaximumSize(new java.awt.Dimension(50, 17));
        fecha_siembra.setMinimumSize(new java.awt.Dimension(50, 17));
        fecha_siembra.setOpaque(true);
        fecha_siembra.setPreferredSize(new java.awt.Dimension(50, 17));

        fecha_cosecha.setBackground(new java.awt.Color(255, 255, 255));
        fecha_cosecha.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        fecha_cosecha.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fecha_cosecha.setOpaque(true);

        Bcosechar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Bcosechar.setText("Cosechar");
        Bcosechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BcosecharActionPerformed(evt);
            }
        });

        nombre_cosecha.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        nombre_cosecha.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        B_regresar_mmenu.setText("regresar");
        B_regresar_mmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_regresar_mmenuActionPerformed(evt);
            }
        });

        jLabel1.setText("Sembrado");

        jLabel2.setText("Cosecha");

        jLabel3.setText("Progreso");

        ubicacion.setBackground(new java.awt.Color(255, 255, 255));
        ubicacion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ubicacion.setOpaque(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(B_regresar_mmenu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 323, Short.MAX_VALUE)
                .addComponent(nombre_cosecha, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(422, 422, 422))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(473, 473, 473))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(469, 469, 469))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(434, 434, 434)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(fecha_cosecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(fecha_siembra, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(Bcosechar))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(479, 479, 479)
                        .addComponent(jLabel3)))
                .addContainerGap(430, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(385, 385, 385)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(barra_progreso, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE)
                    .addComponent(ubicacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(nombre_cosecha, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(B_regresar_mmenu)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fecha_siembra, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fecha_cosecha, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(barra_progreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ubicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(Bcosechar)
                .addGap(141, 141, 141))
        );
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Back button event
     * @param evt 
     */
    private void B_regresar_mmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_regresar_mmenuActionPerformed
        returnToHome();
    }//GEN-LAST:event_B_regresar_mmenuActionPerformed

    private void BcosecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BcosecharActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BcosecharActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton B_regresar_mmenu;
    public javax.swing.JButton Bcosechar;
    public javax.swing.JProgressBar barra_progreso;
    public javax.swing.JLabel fecha_cosecha;
    public javax.swing.JLabel fecha_siembra;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel3;
    public javax.swing.JLabel nombre_cosecha;
    public javax.swing.JLabel ubicacion;
    // End of variables declaration//GEN-END:variables


    /**
     * Method to change the actual window to the Home Window
     */
    public void returnToHome(){
        window.remove(this);        
        window.add(entrar);
        window.repaint();
        window.revalidate();
        window.setVisible(true);
    }
    
    /**
     * Method to get in the tracking window with the crop information
     * @param data
     */
    public void goToTrack(HashMap<String,String> data){
        
        this.setSize(1000, 626);
        window.remove(entrar);
        window.add(this);
        window.repaint();
        window.revalidate();
        window.setVisible(true);
        displayData(data);
    }
    
    /**
     * Method to show the crop info in the fields
     * @param data
     */
    public void displayData(HashMap<String,String> data){
        fecha_siembra.setText(data.get("seed_date"));
        fecha_cosecha.setText(data.get("harvest_date"));
        //barra_progreso.setValue(Integer.valueOf(data.get("bar")));
        int i =0;
        int prog=328;
        barra_progreso.setMinimum(0);
        barra_progreso.setMaximum(100);
         String seed = data.get("seed_date");
         String harvest = data.get("harvest_date");
        ubicacion.setText(data.get("location"));
         setprog(seed,harvest);
    }
    
    public void setprog(String seed,String actual)
    {              
        //sembrado                
        String[] fecha_hora = seed.split(" ");
        
        String[] fecha = fecha_hora[0].split("-");
        
        int ano = Integer.parseInt(fecha[0]);
        int mes = Integer.parseInt(fecha[1]);
        int dia = Integer.parseInt(fecha[2]);
        
       //fecha actual
        LocalDateTime now = LocalDateTime.now();  
        DateTimeFormatter formatter = DateTimeFormatter.ISO_DATE_TIME;
        
        String datenow = now.format(formatter);
        
        
        String[] fecha_hora2 = datenow.split("T");
        
        String[] fecha2 = fecha_hora2[0].split("-");
        
        int ano2 = Integer.parseInt(fecha2[0]);
        int mes2 = Integer.parseInt(fecha2[1]);
        int dia2 = Integer.parseInt(fecha2[2]);
        
        
        
        //cosecha
        String harvest ="2019-12-30 13:07:19.29";
                
        String[] fecha_hora3 = harvest.split(" ");
        
        String[] fecha3 = fecha_hora3[0].split("-");
        
        int ano3 = Integer.parseInt(fecha3[0]);
        int mes3 = Integer.parseInt(fecha3[1]);
        int dia3 = Integer.parseInt(fecha3[2]);
        
        //total de tiempo a transcurrir
        int tot = ((ano3-ano)*12+(mes3-mes))*30+(dia3-dia);
        
        //tiempo pasado
        int timepast = ((ano2-ano)*12+(mes2-mes))*30+(dia2-dia);
        
        //porcentaje transcurrido
        int por = (timepast*100)/tot;
        
        
        barra_progreso.setValue(por);
    }
    
    
    
    public int getBarWidth(){
       return barra_progreso.getWidth();
    }
    
    /**
     * Show in a JOptionPane the persistence exceptions (incomplete)
     * @param ex
     */
    public void showPersistenceExceptions(PersistenceException ex){
        if(ex instanceof NoResultException){
            JOptionPane.showMessageDialog(this, "Información no encontrada" , "ERROR", JOptionPane.ERROR_MESSAGE);
        }else if (ex instanceof JDBCConnectionException){
            JOptionPane.showMessageDialog(this, "Error de conexión" , "ERROR", JOptionPane.ERROR_MESSAGE);
        }else{
            JOptionPane.showMessageDialog(this, "Error" , "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }
}


